<?php

namespace Database\Seeders\SeedersV2\UsersSeeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Repositories\Contracts\UserSignatureRepositoryInterface;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeederV2 extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function __construct(
        private UserRepositoryInterface $userRepo,
        private UserSignatureRepositoryInterface $userSignatureRepo,
    ) {}

    public function run(): void
    {
        // signatures
        // id	user_id	signature_uuid	path	created_at	updated_at	

        $users = [
            [
                // 'id'=>1,
                'username' => 'dean.ahmed.nooraldeen',
                'email' => 'deanahmednooraldeen@university.edu',
                'password' => 'Dean@123456',
                'new_password' => null,
                'role' => 'Dean',
                'status' => 'active',
                'person_id' => 1,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_GQuAMZXwNNimCj7s',
            ],
            [
                // 'id'=>2,
                'username' => 'headofdepartment.hod.mohammad',
                'email' => 'headofdepartment.hod.mohammad@university.edu',
                'password' => 'Hod@123456',
                'new_password' => null,
                'role' => 'HeadOfDepartment',
                'status' => 'active',
                'person_id' => 2,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_aBcDeFgHiJkLmNoP
',
            ],
            [
                // 'id'=>3,
                'username' => 'exam.omar',
                'email' => 'examination@university.edu',
                'password' => 'Exam@123456',
                'new_password' => 'Dean@123456',
                'role' => 'Examination',
                'status' => 'active',
                'person_id' => 3,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_qWeRtYuIoPaSdFgH
',
            ],
            [
                // 'id'=>4,
                'username' => 'affairs.khaled',
                'email' => 'studentaffairs@university.edu',
                'password' => 'Affairs@123456',
                'new_password' => 'Dean@123456',
                'role' => 'StudentAffairs',
                'status' => 'active',
                'person_id' => 4,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_LpOkIjUhYgTfReWq',
            ],
            [
                // 'id'=>5,
                'username' => 'dr.ahmad',
                'email' => 'instructor@university.edu',
                'password' => 'Instructor@123456',
                'new_password' => 'Dean@123456',
                'role' => 'Instructor',
                'status' => 'active',
                'person_id' => 5,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_AbCdEfGhIjKlMnOp',
            ],
            [
                // 'id'=>6,
                'username' => 'ta.sarah',
                'email' => 'ta@university.edu',
                'password' => 'Ta@123456',
                'new_password' => 'Dean@123456',
                'role' => 'TeachingAssistant',
                'status' => 'active',
                'person_id' => 6,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_HiJkLmNoPqRsTuVw
',
            ],
            [
                // 'id'=>7,
                'username' => 'student.omar',
                'email' => 'student1@university.edu',
                'password' => 'Student@123456',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 7,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_ZxSaQwEdRfTgYhUj
',
            ],
            [
                // 'id'=>8,
                'username' => 'student.layla',
                'email' => 'student2@university.edu',
                'password' => 'Student@123456',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'pending',
                'person_id' => 8,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_CvBnMqWeRtYuIoPa
',
            ],
            [
                // 'id'=>9,
                'username' => 'ahmad.ali',
                'email' => 'ahmad.ali@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 9,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_pOiUyTrEwQaZsXdC',
            ],
            [
                // 'id'=>10,
                'username' => 'fatima.hussein',
                'email' => 'fatima.hussein@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 10,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_MnBvCxZaLkJaHsGf
',
            ],
            [
                // 'id'=>11,
                'username' => 'youssef.hamwi',
                'email' => 'youssef.hamwi@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 11,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_zXcVbNmAsDfGhJkL',
            ],
            [
                // 'id'=>12,
                'username' => 'noura.hussein',
                'email' => null,
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 12,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_JkLmNoPqRsTuVwXy
',
            ],

            [
                // 'id'=>13,
                'username' => 'mohammed.nour',
                'email' => 'm.nour@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Instructor',
                'status' => 'active',
                'person_id' => 13,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_lKjHgFdSaPoIuYtR
',
            ],
            [
                // 'id'=>14,
                'username' => 'salma.abdelrahman',
                'email' => 's.abdelrahman@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Instructor',
                'status' => 'active',
                'person_id' => 14,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_PlOkIjUhYgTfReD',
            ],
            [
                // 'id'=>15,
                'username' => 'khaled.sayed',
                'email' => 'khaled.sayed@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Instructor',
                'status' => 'active',
                'person_id' => 15,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_SdFgHjKlZx CvBnM
',
            ],
            [
                // 'id'=>16,
                'username' => 'rana.akkad',
                'email' => null,
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'TeachingAssistant',
                'status' => 'inactive',
                'person_id' => 16,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_mNbVcXzLkJaHsGfD
',
            ],

            [
                // 'id'=>17,
                'username' => 'ammar.khatib',
                'email' => 'ammar.khatib@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'TeachingAssistant',
                'status' => 'active',
                'person_id' => 17,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_QsWeRdFtGyHuJiK
',
            ],
            [
                // 'id'=>18,
                'username' => 'lina.azzam',
                'email' => 'lina.azzam@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'pending',
                'person_id' => 18,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_TyUiOpAsDfGhJkLm',
            ],
            [
                // 'id'=>19,
                'username' => 'rami.khatib',
                'email' => null,
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'pending',
                'person_id' => 19,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_LkJaHsGfDqWeRtYu',
            ],


            [
                // 'id'=>20,
                'username' => 'hiba.mustafa',
                'email' => 'hiba.mustafa@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Examination',
                'status' => 'active',
                'person_id' => 20,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_ZnXcVbNmAsDfGhJk
',
            ],
            [
                // 'id'=>21,
                'username' => 'samer.abed',
                'email' => 'samer.abed@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'SystemAdministrator',
                'status' => 'active',
                'person_id' => 21,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_YuIoPaSdFgHjKlZx
',
            ],
            [
                // 'id'=>22,
                'username' => 'duaa.sheikh',
                'email' => null,
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'pending',
                'person_id' => 22,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_AqWsEdRfTgYhUjIk',
            ],


            [
                // 'id'=>23,
                'username' => 'hussam.halabi',
                'email' => 'hussam.halabi@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Instructor',
                'status' => 'inactive',
                'person_id' => 23,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_MnBvCxZaLkJaHsGf',
            ],
            [
                // 'id'=>24,
                'username' => 'maisa.hammoud',
                'email' => 'maisa.hammoud@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'pending',
                'person_id' => 24,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_RsTuVwXyZaBcDeFg',
            ],
            [
                // 'id'=>25,
                'username' => 'basel.nouri',
                'email' => 'basel.nouri@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Student',
                'status' => 'active',
                'person_id' => 25,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_QwErTyUiOpAsDfGf
',
            ],
            [
                // 'id'=>26,
                'username' => 'reem.khoury',
                'email' => 'reem.khoury@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'TeachingAssistant',
                'status' => 'active',
                'person_id' => 26,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_ZxSaQwEdRfTgYhUj',
            ],
            [
                // 'id'=>27,
                'username' => 'ghassan.hafez',
                'email' => 'ghassan.hafez@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Dean',
                'status' => 'active',
                'person_id' => 27,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_DfGhJkLpOiUyTrEw',
            ],
            [
                // 'id'=>28,
                'username' => 'nancy.saleh',
                'email' => 'nancy.saleh@damascusuniv.edu.sy',
                'password' => 'password123',
                'new_password' => 'Dean@123456',
                'role' => 'Dean',
                'status' => 'active',
                'person_id' => 28,
                'last_login' => '2026-09-19',
                'email_verified_at' => '2026-09-19 15:13:02',
                'created_at' => '2026-09-01',
                'signature_uuid' => '20260723_042037_XyZaBcDeFgHiJkL',
            ],

        ];


        foreach ($users as $userData) {
            DB::transaction(function () use ($userData) {
                $roleName = $userData['role'];
                unset($userData['role']);
                $user = $this->userRepo->create($userData);
                $this->userRepo->assignRole($user, $roleName);
                $usersignature = $this->userSignatureRepo->create($user['id'], $userData['signature_uuid'], $userData['path'] ?? 'private/signatures/' . $user['id'] . '/' . $userData['signature_uuid'] . '.png');
            });
        }
    }
}
