<?php

namespace Database\Seeders\SeedersV2\RolesAndPermissionsSeeders;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Database\Seeder;

class RolesAndPermissionsSeederV2 extends Seeder
{
    public function run()
    {
        $deanRole = Role::create(['name' => 'Dean']);
        $headofdepartmentRole = Role::create(['name' => 'HeadOfDepartment']);
        $examinationRole = Role::create(['name' => 'Examination']);
        $studentaffairsRole = Role::create(['name' => 'StudentAffairs']);
        $instructorRole = Role::create(['name' => 'Instructor']);
        $teachingassistantRole = Role::create(['name' => 'TeachingAssistant']);
        $studentRole = Role::create(['name' => 'Student']);
        $administrativeStaffRole = Role::create(['name' => 'AdministrativeStaff']);
        $systemAdministratorRole = Role::create(['name' => 'SystemAdministrator']);

        $permissions = [
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ];

        foreach ($permissions as $permissionsname) {
            Permission::findOrCreate($permissionsname,/* guardName:*/ 'web');
        }

        $deanRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $headofdepartmentRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $examinationRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $studentaffairsRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $instructorRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $teachingassistantRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $studentRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $administrativeStaffRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
        $systemAdministratorRole->givePermissionTo([
            'get my notifications',
            'get my count notifications unread',
            'read notification',
            'read all my notifications',
            'get all users in our system',
            'add user',
            'update user role',
            'delete user',
            'get user permissions',
            'toggle user activation',
            'get schedule',
            'get student courses',
            'get instructor courses',
            'get teaching assistants',
            'get course students',
            'get course materials',
            'upload course material',
            'update course material',
            'delete course material',
            'download course material',
            'get requests In student college',
            'get student requests list',
            'get staff requests list',
            'store request',
            'get student request details',
            'get staff request details',
            'assign request',
            'cancel request',
            'get all requests',
            'review request',
            'get media by request type',
            'approve request',
            'view media',
            'view pdf',
            'get all grades',
            'add grade',
            'get my grades',
            'get grade appeals',
            'process grade appeal',
            'get invoices',
            'pay invoice',
            'handle payment callback',
            'get payment status',
            'get dashboard stats',
            'get audit logs',
            'apply for admission',
            'get my application',
            'get applications',
            'review application',
            'get sanctions',
            'add sanction',
            'update sanction',
            'delete sanction',
            'get sanction types',
            'store sanction type',
            'add document',
            'get student documents',
            'upload signature',
            'upload college logo',
            'upload lecture',
            'get lecture',
            'get lectures by course part',
            'resend verification code',
            'verify verification code',
            'setup account',
            'upload document',
            'complete profile',
            'submit profile',
            'get profile',
            'edit profile',
            'get profile image',
            'change password',
            'forgot password',
            'verify reset code',
            'reset password',
            'get all my grades',
            'get all my sanctions',
            'get sanction details',
            'respond to sanction',
            'get current semester courses',
            'get current year courses',
            'get completed courses',
            'get remaining courses',
            'get academic progress',
            'get student attachments',
            'review student',
            'get pending students',
            'get request types',
            'get requests list',
            'get request details',
            'get course grades',
            'update grade',
            'add grades for one student',
            'get student home',
            'get academic profile',
            'logout',
            'get college courses',
            'add student suggestion',
            'get student suggestion',
        ]);
    }
}
